name: nix
on: [push, pull_request]

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
          - macos
        conan:
          - 1.50.0
          - 1.51.0
    runs-on: ${{ matrix.platform }}-latest
    env:
      build_dir: .build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: choose Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: install Conan
        run: pip install wheel conan==${{ matrix.conan }}
      - name: check environment
        run: |
          echo ${PATH} | tr ':' '\n'
          python --version
          conan --version
          cmake --version
          env
      - name: configure Conan
        run: conan profile new default --detect
      - name: configure Conan on Linux
        if: runner.os == 'Linux'
        run: |
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: install dependencies
        run: |
          mkdir ${build_dir}
          cd ${build_dir}
          conan install .. --build missing --settings build_type=Release --profile:build default --profile:host default
      - name: configure
        run: |
          cd ${build_dir}
          cmake \
            -DCMAKE_TOOLCHAIN_FILE:FILEPATH=conan_toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            ..
